---
title: "Replicate Models"
author: "Colin Linke"
date: "2024-05-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("Code Transformations.R")
data.file.long <- data.file.long %>% mutate( Time = Semester,
                         Semester = as.factor(Semester),
                         Group_transition = as.factor(Group_transition),
                         Group_transition1 = as.factor(Group_transition1),
                         transition_current = as.factor(transition_current))
```



```{r "paper the three models"}

full.model.lmer <- lmer(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Sex*Cluster_current + Semester*Cluster_current + Sex*Semester + Semester + (1 | BARCS_ID), data = data.file.long, na.action = na.exclude, REML = FALSE) 

full.model.lmer.reduced.interactions <- lmer(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  + Semester*Cluster_current + Semester + (1 | BARCS_ID),data = data.file.long, na.action = na.exclude, REML = FALSE)

small.model.lmer <- lmer(GPA ~ Cluster_current * Semester + (1| BARCS_ID), data = data.file.long, na.action = na.exclude, REML = FALSE)

pseudo.trajectory.lmer <- lmer(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + Semester + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * Semester + Group_transition1 * Semester + (1 | BARCS_ID), data = data.file.long, REML = TRUE, na.action = na.exclude)


fm.slope.lmer <- lmer(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Sex*Cluster_current + Time*Cluster_current + Sex*Time + Time + (1 | BARCS_ID), data = data.file.long, na.action = na.exclude, REML = FALSE) 
```

```{r summaries}
summary(full.model.lmer, robust= "hc3", correction = "Sidak")
summary(full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak")
summary(small.model.lmer, robust= "hc3", correction = "Sidak")
summary(pseudo.trajectory.lmer, robust= "hc3", correction = "Sidak")
summary(fm.slope.lmer, robust= "hc3", correction = "Sidak")
```

```{r "Anova and page }
pbkrtest::KRmodcomp(full.model.lmer, full.model.lmer.reduced.interactions)
anova(full.model.lmer.reduced.interactions, full.model.lmer)

c(logLik(full.model.lmer.reduced.interactions), logLik(small.model.lmer), logLik(full.model.lmer.reduced.interactions) > logLik(small.model.lmer))


Anova(full.model.lmer, robust= "hc3", correction = "Sidak")
Anova(full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak")

Anova(pseudo.trajectory.lmer, test.statistic = "F",  robust= "hc3", correction = "Sidak")

```




```{r plots fullmodel}
plot(full.model.lmer)
qqmath(full.model.lmer)

qqnorm(unlist(ranef(full.model.lmer)$BARCS_ID))
qqline(unlist(ranef(full.model.lmer)$BARCS_ID), col = "red")

plot(effect("Cluster_current*Semester", full.model.lmer, robust= "hc3", correction = "Sidak"))

df.fml <- broom::augment_columns(data = data.file.long, x = full.model.lmer, newdata = data.file.long)
fml.fitted.observed1 <- ggplot(df.fml, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("full model") 
fml.fitted.observed1 <- fml.fitted.observed1 + geom_abline(data = df.fml, formula = GPA ~ .fitted, alpha= 0.4, color ="red")

fml.fitted.observed1
fml.fitted.observed1 + facet_wrap(~Semester)
#plot(density(resid(full.model.lmer)))
#acf(resid(full.model.lmer))
```

```{r plots fullmodel reduced interactions}
plot(full.model.lmer.reduced.interactions)
qqmath(full.model.lmer.reduced.interactions)

qqnorm(unlist(ranef(full.model.lmer.reduced.interactions)$BARCS_ID))
qqline(unlist(ranef(full.model.lmer.reduced.interactions)$BARCS_ID), col = "red")

plot(effect("Cluster_current*Semester", full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak"))

df.fmlri <- broom::augment_columns(data = data.file.long, x = full.model.lmer.reduced.interactions, newdata = data.file.long)
fmlri.fitted.observed1 <- ggplot(df.fmlri, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("full model reduced Interactions") 
fmlri.fitted.observed1 <- fmlri.fitted.observed1 + geom_abline(data = df.fmlri, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
fmlri.fitted.observed1
fmlri.fitted.observed1 + facet_wrap(~Semester)

fml.fitted.observed1
fml.fitted.observed1 + facet_wrap(~Semester)
# plot(density(resid(full.model.lmer.reduced.interactions)))
# acf(resid(full.model.lmer.reduced.interactions))
```



```{r plots small model}
plot(small.model.lmer)
qqmath(small.model.lmer)

qqnorm(unlist(ranef(small.model.lmer)$BARCS_ID))
qqline(unlist(ranef(small.model.lmer)$BARCS_ID), col = "red")

plot(effect("Cluster_current*Semester", small.model.lmer, robust= "hc3", correction = "Sidak"))

df.sml <- broom::augment_columns(data = data.file.long, x = small.model.lmer, newdata = data.file.long)
sml.fitted.observed1 <- ggplot(df.sml, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("small model") 
sml.fitted.observed1 <- sml.fitted.observed1 + geom_abline(data = df.sml, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
sml.fitted.observed1
sml.fitted.observed1 + facet_wrap(~Semester)

sml.fitted.observed1
sml.fitted.observed1 + facet_wrap(~Semester)
# plot(density(resid(small.model.lmer)))
# acf(resid(small.model.lmer))

```


```{r plots pseudo trajectory}
plot(pseudo.trajectory.lmer)
qqmath(pseudo.trajectory.lmer)

qqnorm(unlist(ranef(pseudo.trajectory.lmer)$BARCS_ID))
qqline(unlist(ranef(pseudo.trajectory.lmer)$BARCS_ID), col = "red")

plot(effect("Group_transition1", pseudo.trajectory.lmer, robust= "hc3", correction = "Sidak"))

df.pt <- broom::augment_columns(data = data.file.long, x = pseudo.trajectory.lmer, newdata = data.file.long)
pt.fitted.observed1 <- ggplot(df.pt, aes(x = GPA, y=.fitted)) +
  geom_point( alpha = .05) + ggtitle("pseudo trajectory") 
pt.fitted.observed1 <- pt.fitted.observed1 + geom_abline(data = df.pt, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
pt.fitted.observed1
pt.fitted.observed1 + facet_wrap(~Semester)

# plot(density(resid(pseudo.trajectory.lmer)))
# acf(resid(pseudo.trajectory.lmer))

```



```{r "covariates Sex and Smoking page 8"}
plot(effect("Sex", full.model.lmer, robust= "hc3", correction = "Sidak"), main = "full model")
plot(effect("Fager4_binary", full.model.lmer, robust= "hc3", correction = "Sidak"), main = "full model")

plot(effect("Sex", full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak"), main = "full model reduced Interactions")
plot(effect("Fager4_binary", full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak"), main = "full model reduced Interactions")
```




```{r not adjusted data}

full.model.100000.lmer <- lmer(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Sex*Cluster_current + Semester*Cluster_current + Sex*Semester + Semester + (1 | BARCS_ID), data = data.file.100000.long, na.action = na.exclude, REML = FALSE) 

pseudo.trajectory.100000.lmer <- lmer(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + Semester + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * Semester + Group_transition1 * Semester + (1 | BARCS_ID), data = data.file.100000.long, REML = TRUE, na.action = na.exclude)

Anova(pseudo.trajectory.100000.lmer, test.statistic = "F",  robust= "hc3", correction = "Sidak")

plot(full.model.100000.lmer)
qqmath(full.model.100000.lmer)

qqnorm(unlist(ranef(full.model.100000.lmer)$BARCS_ID))
qqline(unlist(ranef(full.model.100000.lmer)$BARCS_ID), col = "red")

plot(effect("Cluster_current*Semester", full.model.100000.lmer, robust= "hc3", correction = "Sidak"))

df.fml.100000 <- broom::augment_columns(data = data.file.100000.long, x = full.model.100000.lmer, newdata = data.file.100000.long)
fml.fitted.observed1 <- ggplot(df.fml.100000, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("full model") 
fml.100000.fitted.observed1 <- fml.fitted.observed1 + geom_abline(data = df.fml.100000, formula = GPA ~ .fitted, alpha= 0.4, color ="red")

fml.100000.fitted.observed1
fml.100000.fitted.observed1 + facet_wrap(~Semester)
#plot(density(resid(full.model.lmer)))
#acf(resid(full.model.lmer))

```










































```{r "function for plots", echo = FALSE}
plot.fun <- function(model, UnabhVar) {
  ls <- list(plot(model),
    qqmath(model),
    c(qqnorm(unlist(ranef(model)$BARCS_ID)) ,qqline(unlist(ranef(model)$BARCS_ID), col = "red")),
    #dotplot(ranef(model)),
    plot(effect(UnabhVar, model, robust= "hc3", correction = "Sidak"))
  )
}
```

```{r plots}
c(plot.fun(full.model.lmer, "Cluster_current*Semester"),
plot.fun(full.model.lmer.reduced.interactions, "Cluster_current*Semester"),
plot.fun(small.model.lmer, "Cluster_current*Semester"),
plot.fun(fm.slope.lmer, "Cluster_current*Time")
)



df.fml <- broom::augment_columns(data = data.file.long, x = full.model.lmer, newdata = data.file.long)
fml.fitted.observed1 <- ggplot(df.fml, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("full model") 
fml.fitted.observed1 <- fml.fitted.observed1 + geom_abline(data = df.fml, formula = GPA ~ .fitted, alpha= 0.4, color ="red")

fml.fitted.observed1
fml.fitted.observed1 + facet_wrap(~Semester)


df.fmlri <- broom::augment_columns(data = data.file.long, x = full.model.lmer.reduced.interactions, newdata = data.file.long)
fmlri.fitted.observed1 <- ggplot(df.fmlri, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("full model reduced Interactions") 
fmlri.fitted.observed1 <- fmlri.fitted.observed1 + geom_abline(data = df.fmlri, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
fmlri.fitted.observed1
fmlri.fitted.observed1 + facet_wrap(~Semester)


df.sml <- broom::augment_columns(data = data.file.long, x = small.model.lmer, newdata = data.file.long)
sml.fitted.observed1 <- ggplot(df.sml, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("small model") 
sml.fitted.observed1 <- sml.fitted.observed1 + geom_abline(data = df.sml, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
sml.fitted.observed1
sml.fitted.observed1 + facet_wrap(~Semester)

df.slope <- broom::augment_columns(data = data.file.long, x = fm.slope.lmer, newdata = data.file.long)
slope.fitted.observed1 <- ggplot(df.slope, aes(x = GPA, y=.fitted))  +
  geom_point( alpha = .05) + ggtitle("slope model") 
slope.fitted.observed1 <- slope.fitted.observed1 + geom_abline(data = df.slope, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
slope.fitted.observed1
slope.fitted.observed1 + facet_wrap(~Semester)


df.pt <- broom::augment_columns(data = data.file.long, x = pseudo.trajectory.lmer, newdata = data.file.long)
pt.fitted.observed1 <- ggplot(df.pt, aes(x = GPA, y=.fitted)) +
  geom_point( alpha = .05) + ggtitle("pseudo trajectory") 
pt.fitted.observed1 <- pt.fitted.observed1 + geom_abline(data = df.pt, formula = GPA ~ .fitted, alpha= 0.4, color ="red")
pt.fitted.observed1
pt.fitted.observed1 + facet_wrap(~Semester)



```





```{r}

plot(pseudo.trajectory.lmer)
qqmath(pseudo.trajectory.lmer)
dotplot(ranef(pseudo.trajectory.lmer))
plot(effect("Group_transition1", pseudo.trajectory.lmer))
```




```{r "covariates Sex and Smoking"}
plot(effect("Sex", full.model.lmer, robust= "hc3", correction = "Sidak"), main = "full model")
plot(effect("Fager4_binary", full.model.lmer, robust= "hc3", correction = "Sidak"), main = "full model")

plot(effect("Sex", full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak"), main = "full model reduced Interactions")
plot(effect("Fager4_binary", full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak"), main = "full model reduced Interactions")
```


```{r}
pbkrtest::KRmodcomp(full.model.lmer, full.model.lmer.reduced.interactions)
anova(full.model.lmer.reduced.interactions, full.model.lmer)

c(logLik(full.model.lmer.reduced.interactions), logLik(small.model.lmer), logLik(full.model.lmer.reduced.interactions) > logLik(small.model.lmer))


Anova(full.model.lmer, robust= "hc3", correction = "Sidak")
Anova(full.model.lmer.reduced.interactions, robust= "hc3", correction = "Sidak")


Anova(pseudo.trajectory.lmer, test.statistic = "F",  robust= "hc3", correction = "Sidak")


```



```{r "smaller model"}
small.model.lm <- lm(GPA ~ Cluster_current * Semester, data = data.file.long, na.action = na.omit)
small.model.lmer <- lmer(GPA ~ Cluster_current * Semester + (1| BARCS_ID), data = data.file.long, REML = FALSE)
small.model.nlme <- lme(GPA ~ Cluster_current * Semester, data = data.file.long, na.action = na.omit, random = ~ 1 | BARCS_ID)

# summary(small.model.lm)
# summary(small.model.lmer)
# summary(small.model.nlme)

plot(small.model.lm)
plot(small.model.lmer)
plot(small.model.nlme)

```
```{r anova}
anova()
```



```{r Anova tests and the like}
Anova(model.paper.pt.lmer, type = "II", test.statistic = "F", correction = "Sidak")
Anova(model.paper.pt.lmer, type = "II", test.statistic = "Chisq", correction = "Sidak")
Anova(model.paper.pt.lmer2, type = "II", test.statistic = "F", correction = "Sidak")
Anova(model.paper.pt.lmer2, type = "II", test.statistic = "Chisq", correction = "Sidak")


Anova(model.paper.pt.lm, type = "II", test.statistic = "F", correction = "Sidak")
Anova(model.paper.pt.lm2, type = "II", test.statistic = "F", correction = "Sidak")


```








```{r obsolet code}
qqmath(full.model.lmer)
dotplot(ranef(full.model.lmer))
#library(effects)
plot(effect("Cluster_current * Semester", full.model.lmer))
#library(sjPlot)
#sjPlot::plot_model(full.model.lmer, type = "re") Doesnt work 
plot(full.model.lmer)


full.model.nlme <- lme(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Sex*Cluster_current + Semester*Cluster_current + Sex*Semester + Semester, data = data.file.long, random = ~ 1 | BARCS_ID, na.action = na.omit )
summary(full.model.nlme)

full.model.nlme.reduced.interactions <- lme(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Semester*Cluster_current + Semester, data = data.file.long, random = ~ 1 | BARCS_ID, na.action = na.omit )


model.paper.pt.lmer <- lmer(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + Semester + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * Semester + Group_transition1 * Semester + (1 | BARCS_ID), data = data.file.long)

model.paper.pt.lmer2 <- lmer(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + as.numeric(Semester) + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * as.numeric(Semester) + Group_transition1 * as.numeric(Semester) + (1 | BARCS_ID), data = data.file.long)

#summary(model.paper.pt.lmer, correction = "Sidak")


model.paper.pt.lm <- lm(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + as.numeric(Semester) + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * as.numeric(Semester) + Group_transition1 * as.numeric(Semester), data = data.file.long)
#Anova(model.paper.pt.lm, test.statistic = "F")

model.paper.pt.lm2 <- lm(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_SEM1 + as.numeric(Semester) + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * as.numeric(Semester) + Group_transition1 * as.numeric(Semester), data = data.file.long)
#Anova(model.paper.pt.lm, test.statistic = "F")

model.paper.pt.nlme <- lme(GPA ~ 1 + Fager4_binary + FH_binary + Sex + Cluster_current + Cluster_SEM1 + Semester + Age1stround + SATMath + SATVerbal + SATWriting + STAI_SELF_Total + BDI_SELF_Total + Parental_SES + Cluster_SEM1 * Semester + Group_transition1 * Semester, random = ~ 1 | BARCS_ID, na.action = na.omit, data = data.file.long)
#summary(model.paper.pt.nlme)

```
