---
output:
  html_document: default
  pdf_document: default
---

```{r import data, echo = FALSE}
source("Code Transformations.R")

```

```{r robustness check 1 small model, echo=FALSE}
sm.nlme.robust1.1 <- lme(GPA ~ Avg_Drinks_current * Semester + Avg_Drinks_current * Avg_MJ_current + Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude)

sm.nlme.robust1.2 <- lme(GPA ~ Avg_Drinks_current * Semester + Avg_Drinks_current * Avg_MJ_current + Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.robust1.3 <- lme(GPA ~ Avg_Drinks_current * Semester + Avg_Drinks_current * Avg_MJ_current + Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE))

sm.nlme.ARMA11 <- lme(GPA ~ Cluster_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.robust1.noSemester <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.robust1.noSemester.time <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current + Avg_Drinks_current*Time + Avg_MJ_current*Time, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.robust1.timeRE <- lme(std_GPA ~ Avg_Drinks_current * Avg_MJ_current + Avg_Drinks_current*Time + Avg_MJ_current*Time, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)

sm.nlme.robust1.timeRECOV <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML", control = list(maxIter = 1000, tolerance = 1e-2, opt = "optim"))
```

```{r}
cowplot::plot_grid(plot(sm.nlme.robust1.1) ,plot(sm.nlme.robust1.2) , plot(sm.nlme.robust1.3) ,plot(sm.nlme.ARMA11))
cowplot::plot_grid(plot(sm.nlme.robust1.noSemester), plot(sm.nlme.robust1.noSemester.time), plot(sm.nlme.robust1.timeRE), plot(sm.nlme.robust1.timeRECOV))


summary(sm.nlme.robust1.1)
summary(sm.nlme.robust1.2)
summary(sm.nlme.robust1.3)
summary(sm.nlme.ARMA11)
summary(sm.nlme.robust1.noSemester)
summary(sm.nlme.robust1.noSemester.time)
summary(sm.nlme.robust1.timeRE)
summary(sm.nlme.robust1.timeRECOV)


AIC_values.sm.r1 <- AIC(sm.nlme.robust1.1, sm.nlme.robust1.2, sm.nlme.robust1.3, sm.nlme.ARMA11, sm.nlme.robust1.noSemester, sm.nlme.robust1.noSemester.time, sm.nlme.robust1.timeRE, sm.nlme.robust1.timeRECOV)

BIC_values.sm.r1 <- BIC(sm.nlme.robust1.1, sm.nlme.robust1.2, sm.nlme.robust1.3, sm.nlme.ARMA11, sm.nlme.robust1.noSemester, sm.nlme.robust1.noSemester.time, sm.nlme.robust1.timeRE, sm.nlme.robust1.timeRECOV)

df_scores_sm.r1 <- data.frame(AIC_values.sm.r1, BIC_values.sm.r1)
df_scores_sm.r1
```

```{r bigger model robust check 1}

fmri.nlme.robust1.1 <- lme(GPA ~ 1 + Avg_Drinks_current*Avg_MJ_current + Avg_MJ_current*Semester + Avg_Drinks_current*Semester + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.robust1.2 <- lme(GPA ~ 1 + Avg_Drinks_current*Avg_MJ_current + Avg_MJ_current*Semester + Avg_Drinks_current*Semester + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.robust1.3 <- lme(GPA ~ 1 + Avg_Drinks_current*Avg_MJ_current + Avg_MJ_current*Semester + Avg_Drinks_current*Semester + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE), 
                     data = data.file.long, na.action = na.exclude)


fmri.nlme.ARMA11 <- lme(GPA ~ 1 + Cluster_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  + Semester*Cluster_current + Semester,
                       random = ~ 1 | BARCS_ID, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.robust1.noSemester <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))


##no convergence
# fmri.nlme.robust1.noSemester.time <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current + Avg_Drinks_current*Time + Avg_MJ_current*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  , random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.robust1.timeRE <- lme(std_GPA ~ Avg_Drinks_current * Avg_MJ_current + Avg_Drinks_current*Time + Avg_MJ_current*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  , random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)


plot(fmri.nlme.robust1.1)
plot(fmri.nlme.robust1.2)
plot(fmri.nlme.robust1.3)
plot(fmri.nlme.ARMA11)
plot(fmri.nlme.robust1.noSemester)
#plot(fmri.nlme.robust1.noSemester.time)
plot(fmri.nlme.robust1.timeRE)


summary(fmri.nlme.robust1.1)
summary(fmri.nlme.robust1.2)
summary(fmri.nlme.robust1.3)
summary(fmri.nlme.ARMA11)
summary(fmri.nlme.robust1.noSemester)
#summary(fmri.nlme.robust1.noSemester.time)
summary(fmri.nlme.robust1.timeRE)


AIC_values.fmri.r1 <- AIC(fmri.nlme.robust1.1, fmri.nlme.robust1.2, fmri.nlme.robust1.3, fmri.nlme.ARMA11, fmri.nlme.robust1.noSemester, fmri.nlme.robust1.timeRE)
BIC_values.fmri.r1 <- BIC(fmri.nlme.robust1.1, fmri.nlme.robust1.2, fmri.nlme.robust1.3, fmri.nlme.ARMA11, fmri.nlme.robust1.noSemester, fmri.nlme.robust1.timeRE)
df_scores_fmri.r1 <- data.frame(AIC_values.fmri.r1, BIC_values.fmri.r1)
df_scores_fmri.r1

```

```{r SM.R1 with log}
sm.nlme.log.robust1.1 <- lme(GPA ~ LOG_Avg_Drinks_current * Semester + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude)

sm.nlme.log.robust1.2 <- lme(GPA ~ LOG_Avg_Drinks_current * Semester + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

# sm.nlme.log.robust1.3 <- lme(GPA ~ LOG_Avg_Drinks_current * Semester + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE))

sm.nlme.log.robust1.noSemester <- lme(GPA ~ LOG_Avg_Drinks_current * Time + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Time, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude)

#no convergence
# sm.nlme.log.robust1.Time <- lme(GPA ~ LOG_Avg_Drinks_current * Time + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Time, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.log.robust1.TimeRE <- lme(GPA ~ LOG_Avg_Drinks_current * Time + LOG_Avg_Drinks_current * LOG_Avg_MJ_current + LOG_Avg_MJ_current * Time, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)

plot(sm.nlme.log.robust1.1)
plot(sm.nlme.log.robust1.2)
#plot(sm.nlme.log.robust1.3)
plot(sm.nlme.ARMA11)
plot(sm.nlme.log.robust1.noSemester)
#plot(sm.nlme.log.robust1.Time)
plot(sm.nlme.log.robust1.TimeRE)



summary(sm.nlme.log.robust1.1)
summary(sm.nlme.log.robust1.2)
#summary(sm.nlme.log.robust1.3)
summary(sm.nlme.ARMA11)
summary(sm.nlme.log.robust1.noSemester)
#summary(sm.nlme.log.robust1.Time)
summary(sm.nlme.log.robust1.TimeRE)


AIC_values.sm.log.r1 <- AIC(sm.nlme.log.robust1.1, sm.nlme.log.robust1.2, sm.nlme.ARMA11, sm.nlme.log.robust1.noSemester, sm.nlme.log.robust1.TimeRE)
BIC_values.sm.log.r1 <- BIC(sm.nlme.log.robust1.1, sm.nlme.log.robust1.2, sm.nlme.ARMA11, sm.nlme.log.robust1.noSemester, sm.nlme.log.robust1.TimeRE)
df_scores_sm.log.r1 <- data.frame(AIC_values.sm.log.r1, BIC_values.sm.log.r1)
df_scores_sm.log.r1
```

```{r bigger model r1 with log}

fmri.nlme.log.robust1.1 <- lme(GPA ~ 1 + LOG_Avg_Drinks_current*Semester + LOG_Avg_Drinks_current*LOG_Avg_MJ_current + LOG_Avg_MJ_current*Semester +  Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.log.robust1.2 <- lme(GPA ~ 1 + LOG_Avg_Drinks_current*Semester + LOG_Avg_Drinks_current*LOG_Avg_MJ_current + LOG_Avg_MJ_current*Semester +  Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.log.robust1.3 <- lme(GPA ~ 1 + LOG_Avg_Drinks_current*Semester + LOG_Avg_Drinks_current*LOG_Avg_MJ_current + LOG_Avg_MJ_current*Semester +  Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES  ,
                       random = ~ 1 | BARCS_ID, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE), 
                     data = data.file.long, na.action = na.exclude)


plot(fmri.nlme.log.robust1.1)
plot(fmri.nlme.log.robust1.2)
plot(fmri.nlme.log.robust1.3)
plot(fmri.nlme.ARMA11)


summary(fmri.nlme.log.robust1.1)
summary(fmri.nlme.log.robust1.2)
summary(fmri.nlme.log.robust1.3)
summary(fmri.nlme.ARMA11)


AIC_values.fmri.log.r1 <- AIC(fmri.nlme.log.robust1.1, fmri.nlme.log.robust1.2, fmri.nlme.log.robust1.3, fmri.nlme.ARMA11)
BIC_values.fmri.log.r1 <- BIC(fmri.nlme.log.robust1.1, fmri.nlme.log.robust1.2, fmri.nlme.log.robust1.3, fmri.nlme.ARMA11)
df_scores_fmri.log.r1 <- data.frame(AIC_values.fmri.log.r1, BIC_values.fmri.log.r1)
df_scores_fmri.log.r1

```

```{r "standardized Data SM"}

sm.nlme.std.robust2.1 <- lme(std_GPA ~ std_Avg_Drinks * Semester + std_Avg_Drinks * std_Avg_MJ + std_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude)

sm.nlme.std.robust2.2 <- lme(std_GPA ~ std_Avg_Drinks * Semester + std_Avg_Drinks * std_Avg_MJ + std_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.robust2.3 <- lme(std_GPA ~ std_Avg_Drinks * Semester + std_Avg_Drinks * std_Avg_MJ + std_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE))

sm.nlme.std.ARMA11 <- lme(std_GPA ~ Cluster_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.noSemester <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.noSemester.time <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + std_Avg_Drinks*Time + std_Avg_MJ*Time, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.noSemester.timeRE <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + std_Avg_Drinks*Time + std_Avg_MJ*Time, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)



plot(sm.nlme.std.robust2.1)
plot(sm.nlme.std.robust2.2)
plot(sm.nlme.std.robust2.3)
plot(sm.nlme.std.ARMA11)
plot(sm.nlme.std.noSemester)
plot(sm.nlme.std.noSemester.time)
plot(sm.nlme.std.noSemester.timeRE)


summary(sm.nlme.std.robust2.1)
summary(sm.nlme.std.robust2.2)
summary(sm.nlme.std.robust2.3)
summary(sm.nlme.std.ARMA11)
summary(sm.nlme.std.noSemester) 
summary(sm.nlme.std.noSemester.time) 
summary(sm.nlme.std.noSemester.timeRE)


AIC_values.sm.std.r2 <- AIC(sm.nlme.std.robust2.1, sm.nlme.std.robust2.2, sm.nlme.std.robust2.3, sm.nlme.ARMA11, sm.nlme.std.noSemester, sm.nlme.std.noSemester.time, sm.nlme.std.noSemester.timeRE)
BIC_values.sm.std.r2 <- BIC(sm.nlme.std.robust2.1, sm.nlme.std.robust2.2, sm.nlme.std.robust2.3, sm.nlme.ARMA11, sm.nlme.std.noSemester, sm.nlme.std.noSemester.time, sm.nlme.std.noSemester.timeRE)
df_scores_sm.std.r2 <- data.frame(AIC_values.sm.std.r2, BIC_values.sm.std.r2)
df_scores_sm.std.r2
```

```{r standardized Data}

sm.nlme.std.log.robust2.1 <- lme(std_GPA ~ std_LOG_Avg_Drinks * Semester + std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude)

sm.nlme.std.log.robust2.2 <- lme(std_GPA ~ std_LOG_Avg_Drinks * Semester + std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.log.robust2.3 <- lme(std_GPA ~ std_LOG_Avg_Drinks * Semester + std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE))

sm.nlme.std.log.ARMA11.2 <- lme(std_GPA ~ Cluster_current * Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.log.noSemester<- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.log.noSemester.time <- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Time + std_LOG_Avg_MJ*Time, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

sm.nlme.std.log.noSemester.timeRE <- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Time + std_LOG_Avg_MJ*Time, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)



plot(sm.nlme.std.log.robust2.1)
plot(sm.nlme.std.log.robust2.2)
plot(sm.nlme.std.log.robust2.3)
plot(sm.nlme.std.ARMA11)
plot(sm.nlme.std.log.noSemester)
plot(sm.nlme.std.log.noSemester.time)
plot(sm.nlme.std.log.noSemester.timeRE)


summary(sm.nlme.std.log.robust2.1)
summary(sm.nlme.std.log.robust2.2)
summary(sm.nlme.std.log.robust2.3)
summary(sm.nlme.ARMA11)

summary(sm.nlme.std.log.noSemester) 
summary(sm.nlme.std.log.noSemester.time) 
summary(sm.nlme.std.log.noSemester.timeRE)


AIC_values.sm.std.log.r2 <- AIC(sm.nlme.std.log.robust2.1, sm.nlme.std.log.robust2.2, sm.nlme.std.log.robust2.3, sm.nlme.ARMA11, sm.nlme.std.log.noSemester, sm.nlme.std.log.noSemester.time, sm.nlme.std.log.noSemester.timeRE)
BIC_values.sm.log.std.r2 <- BIC(sm.nlme.std.log.robust2.1, sm.nlme.std.log.robust2.2, sm.nlme.std.log.robust2.3, sm.nlme.ARMA11, sm.nlme.std.log.noSemester, sm.nlme.std.log.noSemester.time, sm.nlme.std.log.noSemester.timeRE)
df_scores_sm.std.log.r2 <- data.frame(AIC_values.sm.std.log.r2, BIC_values.sm.log.std.r2)
df_scores_sm.std.log.r2
```

```{r }
fmri.nlme.std.robust2.1 <- lme(std_GPA ~ 1 + std_Avg_Drinks*std_Avg_MJ + std_Avg_Drinks*Semester + std_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.std.robust2.2 <- lme(std_GPA ~ 1 + std_Avg_Drinks*std_Avg_MJ + std_Avg_Drinks*Semester + std_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.std.robust2.3 <- lme(std_GPA ~ 1 + std_Avg_Drinks*std_Avg_MJ + std_Avg_Drinks*Semester + std_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE), 
                     data = data.file.long, na.action = na.exclude)


fmri.nlme.std.ARMA11 <- lme(std_GPA ~ Cluster_current * Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.std.noSemester <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.std.noSemester.time <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + std_Avg_Drinks*Time + std_Avg_MJ*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.std.noSemester.timeRE <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + std_Avg_Drinks*Time + std_Avg_MJ*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)



plot(fmri.nlme.std.robust2.1)
plot(fmri.nlme.std.robust2.2)
plot(fmri.nlme.std.robust2.3)
plot(fmri.nlme.std.ARMA11)
plot(fmri.nlme.std.noSemester)
plot(fmri.nlme.std.noSemester.time)
plot(fmri.nlme.std.noSemester.timeRE)


summary(fmri.nlme.std.robust2.1)
summary(fmri.nlme.std.robust2.2)
summary(fmri.nlme.std.robust2.3)
summary(fmri.nlme.std.ARMA11)
summary(fmri.nlme.std.noSemester)
summary(fmri.nlme.std.noSemester.time)
summary(fmri.nlme.std.noSemester.timeRE)


AIC_values.fmri.std.r2 <- AIC(fmri.nlme.std.robust2.1, fmri.nlme.std.robust2.2, fmri.nlme.std.robust2.3, fmri.nlme.std.ARMA11, fmri.nlme.std.noSemester, fmri.nlme.std.noSemester.time, fmri.nlme.std.noSemester.timeRE)
BIC_values.fmri.std.r2  <- BIC(fmri.nlme.std.robust2.1, fmri.nlme.std.robust2.2, fmri.nlme.std.robust2.3, fmri.nlme.std.ARMA11, fmri.nlme.std.noSemester, fmri.nlme.std.noSemester.time, fmri.nlme.std.noSemester.timeRE)
df_scores_fmri.std.r2 <- data.frame(AIC_values.fmri.std.r2, BIC_values.fmri.std.r2)
df_scores_fmri.std.r2
```

```{r }
fmri.nlme.std.log.robust2.1 <- lme(std_GPA ~ 1 + std_LOG_Avg_Drinks*std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.std.log.robust2.2 <- lme(std_GPA ~ 1 + std_LOG_Avg_Drinks*std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), 
                     data = data.file.long, na.action = na.exclude)

fmri.nlme.std.log.robust2.3 <- lme(std_GPA ~ 1 + std_LOG_Avg_Drinks*std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester  + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES,
                       random = ~ 1 | BARCS_ID, correlation = corExp(form = ~ Time| BARCS_ID, nugget = TRUE), 
                     data = data.file.long, na.action = na.exclude)


fmri.nlme.std.log.noSemester <- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.std.log.noSemester.time <- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Time + std_LOG_Avg_MJ*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

fmri.nlme.std.log.noSemester.timeRE <- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_Drinks*Time + std_LOG_Avg_MJ*Time + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1 + Time| BARCS_ID, data = data.file.long, na.action = na.exclude)



plot(fmri.nlme.std.robust2.1)
plot(fmri.nlme.std.robust2.2)
plot(fmri.nlme.std.robust2.3)
plot(fmri.nlme.std.ARMA11)
plot(fmri.nlme.std.noSemester)
plot(fmri.nlme.std.noSemester.time)
plot(fmri.nlme.std.noSemester.timeRE)


summary(fmri.nlme.std.robust2.1)
summary(fmri.nlme.std.robust2.2)
summary(fmri.nlme.std.robust2.3)
summary(fmri.nlme.std.ARMA11)
summary(fmri.nlme.std.noSemester)
summary(fmri.nlme.std.noSemester.time)
summary(fmri.nlme.std.noSemester.timeRE)


AIC_values.fmri.std.log.r2 <- AIC(fmri.nlme.std.log.robust2.1, fmri.nlme.std.log.robust2.2, fmri.nlme.std.log.robust2.3, fmri.nlme.std.ARMA11, fmri.nlme.std.log.noSemester, fmri.nlme.std.log.noSemester.time, fmri.nlme.std.log.noSemester.timeRE)
BIC_values.fmri.std.log.r2  <- BIC(fmri.nlme.std.log.robust2.1, fmri.nlme.std.log.robust2.2, fmri.nlme.std.log.robust2.3, fmri.nlme.std.ARMA11, fmri.nlme.std.log.noSemester, fmri.nlme.std.log.noSemester.time, fmri.nlme.std.log.noSemester.timeRE)
df_scores_fmri.std.log.r2 <- data.frame(AIC_values.fmri.std.log.r2, BIC_values.fmri.std.log.r2)
df_scores_fmri.std.log.r2
```

```{r}
sm.nlme.robust1.noSemester.2 <- lme(GPA ~ Avg_Drinks_current * Avg_MJ_current + I(Avg_Drinks_current^2) + I(Avg_MJ_current != 0), random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID))

plot(sm.nlme.robust1.noSemester.2)
summary(sm.nlme.robust1.noSemester.2)
```

```{r}
outlier.removed <- data.file.long %>% filter(Avg_Drinks_current <= 150)

## small model outlier

outlier.removed <- outlier.removed %>%
  group_by(Semester) %>%
  mutate(mean_Avg_Drinks = Avg_Drinks_current - mean(Avg_Drinks_current),
         std_Avg_Drinks = mean_Avg_Drinks / sd(Avg_Drinks_current),
         mean_LOG_Avg_Drinks = LOG_Avg_Drinks_current - mean(LOG_Avg_Drinks_current),
         std_LOG_Avg_Drinks = mean_LOG_Avg_Drinks / sd(LOG_Avg_Drinks_current),
         mean_Avg_MJ = Avg_MJ_current - mean(Avg_MJ_current, na.rm = TRUE),
         std_Avg_MJ = mean_Avg_MJ / sd(Avg_MJ_current, na.rm = TRUE),
         mean_LOG_Avg_MJ = LOG_Avg_MJ_current - mean(LOG_Avg_MJ_current, na.rm = TRUE),
         std_LOG_Avg_MJ = mean_LOG_Avg_MJ / sd(LOG_Avg_MJ_current, na.rm = TRUE),
         mean_GPA = GPA - mean(GPA, na.rm = TRUE),
         std_GPA = mean_GPA / sd(GPA, na.rm = TRUE) )


sm.outlier.log<- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier<- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")



sm.outlier.semester.log <- lme(std_GPA ~ std_LOG_Avg_Drinks * Semester + std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


sm.outlier.semester <- lme(std_GPA ~ std_Avg_Drinks * Semester + std_Avg_Drinks * std_Avg_MJ + std_Avg_MJ * Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed2 <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ - std_Avg_MJ + std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


plot(sm.outlier.log)
plot(sm.outlier)
plot(sm.outlier.semester.log)
plot(sm.outlier.semester)
plot(sm.outlier.mixed)
plot(sm.outlier.mixed2)
plot(sm.outlier.barebones)

summary(sm.outlier.log)
summary(sm.outlier)
summary(sm.outlier.semester.log)
summary(sm.outlier.semester)
summary(sm.outlier.mixed)
summary(sm.outlier.mixed2)
summary(sm.outlier.barebones)

AIC_sm.outlier <- AIC(sm.outlier.log, sm.outlier, sm.outlier.semester.log, sm.outlier.semester, sm.outlier.mixed, sm.outlier.mixed2, sm.outlier.barebones)
BIC_sm.outlier <- BIC(sm.outlier.log, sm.outlier, sm.outlier.semester.log, sm.outlier.semester, sm.outlier.mixed, sm.outlier.mixed2, sm.outlier.barebones)
df.sm.out <- data.frame(AIC_sm.outlier, BIC_sm.outlier)
df.sm.out
```

```{r sm tests}
sm.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Anova(sm.outlier.mixed)
anova(sm.outlier.mixed, sm.outlier.barebones)

sm.outlier.mixed.Semester1 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.Semester2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ*Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.Semester3 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.Semester4 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ*Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.Semester5 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester - Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.timeC1 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Time + std_Avg_Drinks * Time, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.timeC2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ  + std_Avg_Drinks * Time, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.timeC3 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Time, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

sm.outlier.mixed.timeC4 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ * Time, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


anova(sm.outlier.mixed, sm.outlier.mixed.Semester1)
anova(sm.outlier.mixed, sm.outlier.mixed.Semester2)
anova(sm.outlier.mixed, sm.outlier.mixed.Semester3)
anova(sm.outlier.mixed, sm.outlier.mixed.Semester4)
anova(sm.outlier.mixed, sm.outlier.mixed.Semester5)
chooseTimeSemester1 <- data.frame(AIC(sm.outlier.mixed.Semester1, sm.outlier.mixed.Semester2, sm.outlier.mixed.Semester3, sm.outlier.mixed.Semester4, sm.outlier.mixed.Semester5, sm.outlier.mixed.timeC1, sm.outlier.mixed.timeC2, sm.outlier.mixed.timeC3, sm.outlier.mixed.timeC4), BIC(sm.outlier.mixed.Semester1, sm.outlier.mixed.Semester2, sm.outlier.mixed.Semester3, sm.outlier.mixed.Semester4, sm.outlier.mixed.Semester5, sm.outlier.mixed.timeC1, sm.outlier.mixed.timeC2, sm.outlier.mixed.timeC3, sm.outlier.mixed.timeC4))


sm.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")

sm.outlier.mixed.time <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1 + Time| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML", control = list(maxIter = 1000, tolerance = 1e-3, opt = "optim"))

anova(sm.outlier.mixed, sm.outlier.mixed.time)
plot(sm.outlier.mixed.time)  ###BAD!

```

```{r fmri}

fmri.outlier.log<- lme(std_GPA ~ std_LOG_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier<- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")



fmri.outlier.semester.log <- lme(std_GPA ~ std_LOG_Avg_Drinks * Semester + std_LOG_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ * Semester + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


fmri.outlier.semester <- lme(std_GPA ~ std_Avg_Drinks * Semester + std_Avg_Drinks * std_Avg_MJ + std_Avg_MJ * Semester + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed2 <- lme(std_GPA ~ std_Avg_Drinks * std_Avg_MJ - std_Avg_MJ + std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


plot(fmri.outlier.log)
plot(fmri.outlier)
plot(fmri.outlier.semester.log)
plot(fmri.outlier.semester)
plot(fmri.outlier.mixed)
plot(fmri.outlier.mixed2)
plot(fmri.outlier.barebones)

summary(fmri.outlier.log)
summary(fmri.outlier)
summary(fmri.outlier.semester.log)
summary(fmri.outlier.semester)
summary(fmri.outlier.mixed)
summary(fmri.outlier.mixed2)
summary(fmri.outlier.barebones)

AIC_fmri.outlier <- AIC(fmri.outlier.log, fmri.outlier, fmri.outlier.semester.log, fmri.outlier.semester, fmri.outlier.mixed, fmri.outlier.mixed2, fmri.outlier.barebones)
BIC_fmri.outlier <- BIC(fmri.outlier.log, fmri.outlier, fmri.outlier.semester.log, fmri.outlier.semester, fmri.outlier.mixed, fmri.outlier.mixed2, fmri.outlier.barebones)
df.fmri.out <- data.frame(AIC_fmri.outlier, BIC_fmri.outlier)
df.fmri.out
```

```{r fmri tests}
fmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATVerbal + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.SAT <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATTotal + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.noSAT <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.noVerbal <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

AIC(fmri.outlier.mixed, fmri.outlier.mixed.SAT, fmri.outlier.mixed.noSAT, fmri.outlier.mixed.noVerbal)
BIC(fmri.outlier.mixed, fmri.outlier.mixed.SAT, fmri.outlier.mixed.noSAT, fmri.outlier.mixed.noVerbal)


fmri.outlier.mixed.reduced <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.reduced2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.reduced3 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + SATMath + SATWriting + Fager4_binary + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")



data.frame(AIC(fmri.outlier.mixed.noVerbal, fmri.outlier.mixed.reduced, fmri.outlier.mixed.reduced2, fmri.outlier.mixed.reduced3), BIC(fmri.outlier.mixed.noVerbal, fmri.outlier.mixed.reduced, fmri.outlier.mixed.reduced2, fmri.outlier.mixed.reduced3))

plot(fmri.outlier.mixed.noVerbal)
summary(fmri.outlier.mixed.noVerbal)

fmri.outlier.mixed.noVerbal <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

anova(fmri.outlier.mixed.noVerbal, fmri.outlier.barebones)
```

```{r fmri tests without the interaction}
fmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.Semester1 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

# fmri.outlier.mixed.Semester2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
#                                     , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.Semester3 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_Avg_Drinks*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.Semester4 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.Semester5 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester - Semester + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.timeC1 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_Avg_Drinks * Time + std_LOG_Avg_MJ* Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.timeC2 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_LOG_Avg_MJ* Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

fmri.outlier.mixed.timeC3 <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + std_Avg_Drinks * Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

anova(fmri.outlier.mixed, fmri.outlier.mixed.Semester1)
# anova(fmri.outlier.mixed, fmri.outlier.mixed.Semester2)
anova(fmri.outlier.mixed, fmri.outlier.mixed.Semester3)
anova(fmri.outlier.mixed, fmri.outlier.mixed.Semester4)
anova(fmri.outlier.mixed, fmri.outlier.mixed.Semester5)
anova(fmri.outlier.mixed, fmri.outlier.mixed.timeC1)
anova(fmri.outlier.mixed, fmri.outlier.mixed.timeC2)
anova(fmri.outlier.mixed, fmri.outlier.mixed.timeC3)
anova(fmri.outlier.mixed.timeC1, fmri.outlier.mixed.timeC2)
anova(fmri.outlier.mixed.timeC1, fmri.outlier.mixed.timeC3)
chooseTimeSemester2 <- data.frame(AIC(fmri.outlier.mixed.Semester1, fmri.outlier.mixed.Semester3, fmri.outlier.mixed.Semester4, fmri.outlier.mixed.Semester5, fmri.outlier.mixed.timeC1, fmri.outlier.mixed.timeC2, fmri.outlier.mixed.timeC3), BIC(fmri.outlier.mixed.Semester1, fmri.outlier.mixed.Semester3, fmri.outlier.mixed.Semester4, fmri.outlier.mixed.Semester5, fmri.outlier.mixed.timeC1, fmri.outlier.mixed.timeC2, fmri.outlier.mixed.timeC3))


fmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                          , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")


fmri.outlier.mixed.time <- lme(std_GPA ~ std_Avg_Drinks + std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                               , random = ~ 1 + Time| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML", control = list(maxIter = 1000, tolerance = 1e-3, opt = "optim"))

anova(fmri.outlier.mixed, fmri.outlier.mixed.time)
plot(fmri.outlier.mixed.time)

```

```{r "with interaction (excersise in futility, the interaction is shown that it shouldn't be included earlier)"}
Afmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


Afmri.outlier.mixed.Semester1 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.Semester2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.Semester3 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.Semester4 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ*Semester+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.Semester5 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester - Semester + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                                    , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")


Afmri.outlier.mixed.timeC1 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks * Time + std_LOG_Avg_MJ* Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.timeC2 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_LOG_Avg_MJ* Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.timeC3 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks * Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

Afmri.outlier.mixed.timeC4 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ * Time + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "ML")

anova(Afmri.outlier.mixed, Afmri.outlier.mixed.Semester1)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.Semester2)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.Semester3)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.Semester4)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.Semester5)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.timeC1)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.timeC2)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.timeC3)
anova(Afmri.outlier.mixed, Afmri.outlier.mixed.timeC4)
anova(Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC2)
anova(Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC3)
anova(Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC4)
anova(Afmri.outlier.mixed.timeC4, Afmri.outlier.mixed.timeC2)
anova(Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC3)
chooseTimeSemester3 <- data.frame(AIC(Afmri.outlier.mixed.Semester1, Afmri.outlier.mixed.Semester2, Afmri.outlier.mixed.Semester3, Afmri.outlier.mixed.Semester4, Afmri.outlier.mixed.Semester5, Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC2, Afmri.outlier.mixed.timeC3, Afmri.outlier.mixed.timeC4), BIC(Afmri.outlier.mixed.Semester1, Afmri.outlier.mixed.Semester2, Afmri.outlier.mixed.Semester3, Afmri.outlier.mixed.Semester4, Afmri.outlier.mixed.Semester5, Afmri.outlier.mixed.timeC1, Afmri.outlier.mixed.timeC2, Afmri.outlier.mixed.timeC3, Afmri.outlier.mixed.timeC4))


fmri.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                          , random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")

fmri.outlier.mixed.time <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ+ Sex + Age1stround + SATMath + SATWriting + Fager4_binary + FH_binary + STAI_SELF_Total + BDI_SELF_Total + Parental_SES
                               , random = ~ 1 + Time| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML", control = list(maxIter = 1000, tolerance = 1e-3, opt = "optim"))

anova(fmri.outlier.mixed, fmri.outlier.mixed.time)
plot(fmri.outlier.mixed.time)
```

```{r see the best way for the time / Semester variable to be included}

chooseTimeSemester1
chooseTimeSemester2
chooseTimeSemester3
plot(sm.outlier.mixed.timeC3)
plot(sm.outlier.mixed.timeC2)
plot(sm.outlier.mixed.timeC1)
plot(sm.outlier.mixed.Semester5)
plot(fmri.outlier.mixed.timeC2)
plot(fmri.outlier.mixed.timeC3)
plot(fmri.outlier.mixed.timeC1)
plot(fmri.outlier.mixed.Semester5)
plot(Afmri.outlier.mixed.timeC2)
plot(Afmri.outlier.mixed.timeC3)
plot(Afmri.outlier.mixed.timeC4)
plot(Afmri.outlier.mixed.Semester5)
```

```{r comparison models}
sm.outlier.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")
sm.full.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")
sm.outlier.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")
sm.full.barebones <- lme(std_GPA ~ std_Avg_Drinks + std_Avg_MJ, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")
sm.outlier.mixed.Semester5 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester - Semester, random = ~ 1| BARCS_ID, data = outlier.removed, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")
sm.full.mixed.Semester5 <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ + std_Avg_Drinks*Semester + std_LOG_Avg_MJ*Semester - Semester, random = ~ 1| BARCS_ID, data = data.file.long, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")

summary(sm.outlier.mixed)
summary(sm.full.mixed)
summary(sm.outlier.barebones)
summary(sm.full.barebones)
summary(sm.outlier.mixed.Semester5)
summary(sm.full.mixed.Semester5)

plot(sm.outlier.mixed)
plot(sm.full.mixed)
plot(sm.outlier.barebones)
plot(sm.full.barebones)
plot(sm.outlier.mixed.Semester5)
plot(sm.full.mixed.Semester5)



# summary(fmri.outlier.mixed)
# summary(fmri.outlier.mixed.noInt)
# anova(fmri.outlier.mixed.noVerbal, fmri.outlier.mixed.noInt)
```

```{r}

sm.imputed.mixed <- lme(std_GPA ~ std_Avg_Drinks * std_LOG_Avg_MJ, random = ~ 1| BARCS_ID, data = imputed_values, na.action = na.exclude, correlation = corARMA(p = 1, q = 1, form = ~ Time| BARCS_ID), method = "REML")

plot(sm.imputed.mixed)
summary(sm.imputed.mixed)



```

```{r "gamlss"}
library(gamlss)
outlier.removed2 <- outlier.removed %>% select(BARCS_ID, GPA, Avg_Drinks_current, Avg_MJ_current, Sex, Time, Semester, Age1stround, SATMath, SATWriting, Fager4_binary, BDI_SELF_Total, FH_binary)
gamlss1 <- gamlss(formula = GPA ~ pb(Avg_Drinks_current) * pb(Avg_MJ_current) + random(BARCS_ID) + Sex + Time, 
                  sigma.formula = ~pb(Avg_Drinks_current) * pb(Avg_MJ_current) + Sex + Time + Age1stround + SATMath + SATWriting + Avg_Drinks_current + Avg_MJ_current
                    ,data = na.omit(outlier.removed2), na.action = na.exclude, family = BCCG)
summary(gamlss1)
plot(residuals(gamlss1), fitted(gamlss1),
     xlab = "fitted values", ylab = "Residuals")

gamlss2 <- gamlss(formula = GPA ~ pb(Avg_Drinks_current) * pb(Avg_MJ_current) + random(BARCS_ID) + Time, 
                  sigma.formula = ~pb(Avg_Drinks_current) * pb(Avg_MJ_current) - pb(Avg_Drinks_current) + Sex + Semester + Age1stround + SATMath + SATWriting,
                  nu.formula = ~pb(Avg_Drinks_current) * pb(Avg_MJ_current) - pb(Avg_Drinks_current) + Sex + Semester + Age1stround + SATMath + SATWriting
                    ,data = na.omit(outlier.removed2), na.action = na.exclude, family = BCCG, method = CG())

summary(gamlss2)
plot(residuals(gamlss2), fitted(gamlss2),
     xlab = "fitted values", ylab = "Residuals")

gamlss3 <- gamlss(formula = GPA ~ pb(Avg_Drinks_current) * pb(Avg_MJ_current) * Time + random(BARCS_ID), 
                  sigma.formula = ~pb(Avg_Drinks_current) * pb(Avg_MJ_current) - pb(Avg_Drinks_current) + Sex + Time + Age1stround + SATMath + SATWriting,
                  nu.formula = ~Time * pb(Avg_MJ_current) + SATMath + SATWriting
                    ,data = na.omit(outlier.removed2), na.action = na.exclude, family = BCCG)
summary(gamlss3)
plot(residuals(gamlss3), fitted(gamlss3),
     xlab = "fitted values", ylab = "Residuals")

gamlss4 <- gamlss(formula = GPA ~ pb(Avg_Drinks_current) * pb(Avg_MJ_current) * Time + random(BARCS_ID), 
                  sigma.formula = ~pb(Avg_Drinks_current) * pb(Avg_MJ_current) - pb(Avg_Drinks_current) + Sex + Time + Age1stround + SATMath + SATWriting + Fager4_binary + BDI_SELF_Total + FH_binary,
                  nu.formula = ~Time * pb(Avg_MJ_current) + SATMath + SATWriting + Sex + Fager4_binary + BDI_SELF_Total + FH_binary ,
                  tau.formula = ~ Time * pb(Avg_MJ_current) + SATMath + SATWriting + Sex + Fager4_binary + BDI_SELF_Total + FH_binary,
                  data = na.omit(outlier.removed2), na.action = na.exclude, family = BCCG,  
                  control = gamlss.control(n.cyc = 40))

summary(gamlss4)
plot(residuals(gamlss4), fitted(gamlss4),
     xlab = "fitted values", ylab = "Residuals")

```
